### ISSUE TITLE
Set up JNDI resources for common backing services

### ISSUE THREAD

**Issue by jesperfj** [heroku/webapp-runner#10]
It is common, and very convenient to configure external service configuration via environment variables. For example, access to a database can be provided via an environment variable like so:

```
DATABASE_URL=postgres://un:pw@hostname:port/database
```

It would be nice if webapp-runner could automatically configure a JNDI DataSource at java:comp/env/jdbc/default for this datasource. If the URL is formatted as `DATABASE_SOMENAME_URL` then the data source should be configured at java:comp/env/jdbc/somename.

**Comment by Malax** [comment]
Hello! Since this is an old issue and many things have changed since it was opened I will close it for now. Feel absolutely free to re-open it if it is still relevant so we can work on it! :)
