### ISSUE TITLE
-AmaxPostSize=-1  not work, cannot post large content

### ISSUE THREAD

**Issue by jk2K** [heroku/webapp-runner#165]
my start command
```bash
java -jar ./webapp-runner.jar -AmaxPostSize=-1 ./target/demopostbigcontent-0.0.1-SNAPSHOT.war
```

jetbrains http client editor
```plain
POST 127.0.0.1:8080/greeting/big-content
Content-Type: text/plain

< ./data.json

###

POST 127.0.0.1:8080/greeting/big-content
Content-Type: text/plain

< ./smalldata.json
```

data.json 2.6 MB
smalldata.json 3k

my code, Spring Boot framework

Greeting.java
```java
public class Greeting {
    private final long id;
    private final String content;

    public Greeting(long id, String content) {
        this.id = id;
        this.content = content;
    }

    public long getId() {
        return id;
    }

    public String getContent() {
        return content;
    }
}
```

GreetingController.java
```java
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.concurrent.atomic.AtomicLong;

@RestController
public class GreetingController {
    private static final String template = "Hello, %s!";
    private final AtomicLong counter = new AtomicLong();

    @RequestMapping("/greeting/big-content")
    public Greeting greetingBigContent(@RequestBody String payload) {
        return new Greeting(counter.incrementAndGet(),
                payload);
    }
}
```

submit data.json failed

![image](https://user-images.githubusercontent.com/4025839/72050033-25c3f200-32fb-11ea-9c35-ef73fea94b50.png)

submit smalldata.json success

![image](https://user-images.githubusercontent.com/4025839/72050065-36746800-32fb-11ea-80b6-776889aa4375.png)

I tried adjusting many tomcat parameters but none worked, for example
```bash
java -jar ./webapp-runner.jar -AmaxPostSize=-1 -AmaxSwallowSize=-1 -AconnectionTimeout=100000 -AmaxSavePostSize=-1 -AmaxParameterCount=-1 ./target/demopostbigcontent-0.0.1-SNAPSHOT.war
```

How to solve this problem? please help me, thanks

**Comment by Malax** [comment]
Hello @jk2K,

this is most likely not an issue with webapp-runner itself. Additionally, I can see that the content length seems to be correct for the first example. However, If you can provide a standalone, runnable repository I can take a look real quick.

**Comment by jk2K** [comment]
https://github.com/jk2K/demopostbigcontent, test repo is here, thanks

**Comment by jk2K** [comment]
![image](https://user-images.githubusercontent.com/4025839/72052527-4b9fc580-3300-11ea-8c41-2769fb34cf44.png)

**Comment by Malax** [comment]
This works without any issues for me. I used webapp-runner `9.0.30.0` and [httpie](https://httpie.org/) to send requests like this:

`http post localhost:8080/greeting/big-content content=@./projects/demopostbigcontent/src/test/data.json`

**Comment by jk2K** [comment]
have you tried webapp-runner 8.5?

**Comment by Malax** [comment]
I didn't. But I tested it now with `8.5.50.0` and it works as well.

**Comment by jk2K** [comment]
I use curl to send requests like this:
```bash
curl -X POST 127.0.0.1:8080/greeting/big-content -H 'Content-Type: text/plain' -d @/pathto/java/demopostbigcontent/src/test/data.json > /tmp/1.log
```

the results is ok, maybe a bug in JetBrains http client editor

but this brings up a new issue, according to [complete list of HTTP connector attributes](https://tomcat.apache.org/tomcat-8.5-doc/config/http.html)   If maxPostSize not specified, this attribute is set to 2097152 (2 megabytes)

my `data.json` size is 2.4MB，Why can I upload successfully without any error ?

**Comment by Malax** [comment]
> Why can I upload successfully without any error ?

`maxPostSize` is only used when parsing `application/x-www-form-urlencoded` payloads. Since you explicitly send a `Content-Type: text/plain` that restriction has no effect. Omitting `-H 'Content-Type: text/plain'` in your example returns a `400` (Bad Request) as expected for payloads > 2MiB.

**Comment by jk2K** [comment]
thanks, I learned something new

**Comment by jk2K** [comment]
I updated the demo repo and can now verify that `-AmaxPostSize=-1` does not work for `application/x-www-form-urlencoded`, Please take a look

**Comment by Malax** [comment]
Hello! Since this is an old issue and many things have changed since it was opened I will close it for now. Feel absolutely free to re-open it if it is still relevant so we can work on it! :)
