### ISSUE TITLE
Possibility to select http connector

### ISSUE THREAD

**Issue by ghost** [heroku/webapp-runner#207]
Hi,
Currently, the webapp-runner has the http "nio" connector hard-coded. Tomcat also offers a "nio2" and an "apr" connector. Would it be possible to make that configurable? For the "apr" connector, the "AprLifecycleListener" must be set up with correct attributes (for example, switch off ssl, switch off openssl and enable apr), and the native libraries "tcnative" and "apr" must be available in the java.library.path.

**Comment by jkutner** [comment]
@tbf2000 that seems like something we could do. How similar is the interface for each connector?

If you're interested in to prototyping it [this is a good place to start](https://github.com/heroku/webapp-runner/blob/main/main/src/main/java/webapp/runner/launch/Main.java#L92).

**Comment by tbf2000** [comment]
The interface of the connector is no challenge. You can just set instatiate it using the apr-specific classname:

		String connectorClassName = tomcatNative ? "org.apache.coyote.http11.Http11AprProtocol"
				: "org.apache.coyote.http11.Http11NioProtocol";
		Connector httpConnector = new Connector(connectorClassName);

But before you do that, you have to add the AprLifecycleListener to the Tomcat instance:

		LifecycleListener[] lifecycleListeners = tomcat.getServer().findLifecycleListeners();
		AprLifecycleListener aprLifecycleListener = null;
		if (null != lifecycleListeners) {
			for (LifecycleListener lifecycleListener : lifecycleListeners) {
				if (lifecycleListener instanceof AprLifecycleListener) {
					aprLifecycleListener = (AprLifecycleListener) lifecycleListener;
				}
			}
		}
		if (null == aprLifecycleListener) {
			aprLifecycleListener = new AprLifecycleListener();
			tomcat.getServer().addLifecycleListener(aprLifecycleListener);
		}
		aprLifecycleListener.setUseAprConnector(true);
		aprLifecycleListener.setSSLEngine("off");
		aprLifecycleListener.setUseOpenSSL(false);

**Comment by Malax** [comment]
Hello! Since this is an old issue and many things have changed since it was opened I will close it for now. Feel absolutely free to re-open it if it is still relevant so we can work on it! :)
