### ISSUE TITLE
Increase Heroku slugsize

### ISSUE THREAD

**Issue by lucaformisano** [heroku/webapp-runner#208]
Hi i'm trying to use the package in a maven project, when i try to deploy to heroku without webapp-runner my slugsize is 365MB when i add the webapp-runner plugin to my pom file the slugsize increase to 1.9gb and heroku deploy fails....any hints/help?
Thanks

**Comment by Malax** [comment]
Hello @lucaformisano, since this issue is several years old (apologies!), I will close it now. Feel free to re-open if necessary! Thanks!
