### ISSUE TITLE
support for proxy

### ISSUE THREAD

**Issue by kvlou** [heroku/webapp-runner#26]
In most cases tomcat runs behind a proxy, one of them would be for SSL offloading.
We have a modified version of the runner that looks up BASE_URL and sets the proxy parameters in embedded tomcat. 

Would you be interested in a pull request John?

**Comment by howardfackrell** [comment]
+1, I'd also like to see support for a proxy

**Comment by jkutner** [comment]
I would merge this. Can you create a PR from the diff?

**Comment by howardfackrell** [comment]
Sure, I'll do that.

**Comment by Malax** [comment]
Hello! Since this is an old issue and many things have changed since it was opened I will close it for now. Feel absolutely free to re-open it if it is still relevant so we can work on it! :)
