### ISSUE TITLE
execution error

### ISSUE THREAD

**Issue by kamalesreekanth** [heroku/webapp-runner#268]
Cannot invoke "java.sql.Statement.executeQuery(String)" because "this.st" is null
Invalid username/password 

please help to sort out this error.... from the last 6 days I'm facing these......

**Comment by Malax** [comment]
Hello @kamalesreekanth, I'm not sure how this error would relate to the code in this repository. Since this issue is several months old (apologies!), I will close it now. Feel free to re-open if necessary! Thanks!
