### ISSUE TITLE
Please consider adding Tomcat 10.1 support

### ISSUE THREAD

**Issue by gpotagal-WellSky** [heroku/webapp-runner#359]

**Comment by Malax** [comment]
Hi @gpotagal-WellSky!

Can you share which Tomcat 10.1 features are important to your app? It would help us to prioritise this feature. Thanks! :)

**Comment by cor3000** [comment]
To me webapp-runner is a tool I heavily use during development. Being able to test/compare out multiple tomcat versions just by flipping a maven dependency is quite a feature.
So personally I find: having additional versions available is of importance by itself and independent of the specific tomcat features. Sometimes there's even a bug in tomcat and being able to pinpoint quickly which version introduced a behavior is great.
Also testing whether a web application will work on the next major tomcat version is important. One day we might be forced to update to tomcat 10 (for whatever reason, e.g. having to switch to jakarta-ee), then being able to verify the application already works before it's too late would be a feature by itself.

**Comment by Malax** [comment]
@gpotagal-WellSky, @cor3000 thanks for your input on the matter! Spring Boot 3.x is quite the argument. I'll update this issue when we have a plan how and when to support Tomcat 10! :)

**Comment by Malax** [comment]
Quick update for @gpotagal-WellSky, @cor3000 and everyone else interested: there will be a webapp-runner for Tomcat 10! 🎉 I don't have a concrete timeline yet, but I hope we can ship this sooner rather than later given the Spring Boot EOL. I will keep you posted!

**Comment by gpotagal-WellSky** [comment]
@Malax - update is not complex - I've created a fork and created a pull request: https://github.com/heroku/webapp-runner/pull/375/  There's a small race condition in one of the tests with file writes that in our environment caused intermittent failures that I fixed.  @cor3000 - you can test off https://github.com/gpotagal-WellSky/webapp-runner/tree/tomcat10 - happy path tests for us did not show any issues.

**Comment by cor3000** [comment]
@gpotagal-WellSky 
Thanks, I built your branch, created a simple dummy application using our UI framework's jakarta variant, and it seems to run just fine.
I hope your changes, or something equivalent make it into the main repo eventually.

@Malax wow spring boot EOL is quite soon, thanks for the reminder
