### ISSUE TITLE
context root path issues

### ISSUE THREAD

**Issue by jessewriter** [heroku/webapp-runner#80]
omg did I waste lot of time searching google for an answer as to why my dynamic web app would work perfectly on a tomcat server from within eclipse but when I run it with your webapp-runner it would lose the context root 'http://localhost:8080/event/' in my case and just run off localhost:8080/ well this obviously broke all my links.  The solution was dam simple to just define the path option which I didn't know about till I found this page!  My suggestion is some way that webapp-runner can read in the context root defined by eclipse and also I defined it in my pom with a specific warName= event but that and many other experiments all failed to pass through.

**Comment by Jawwad124** [comment]
did you found solution ? In my case getPathInfo is returning null. While it works fine when running application on tomcat server

**Comment by Malax** [comment]
Hello! Since this is an old issue and many things have changed since it was opened I will close it for now. Feel absolutely free to re-open it if it is still relevant so we can work on it! :)
