### ISSUE TITLE
webapp-runner throws NPE on DataSource

### ISSUE THREAD

**Issue by carlomorelli** [heroku/webapp-runner#82]
Hi,

I have a maven Servlet/JSP project with a JDBC Postgres backend.
The project is designed to produce a WAR file with an embedded "META-INF/context.xml" that contains the dataSource factory informations.

If the WAR is deployed manually on a Tomcat installation, everything works fine.

However, if I try to deploy the it file with WebappRunner with the usual procedure:
```
mvn clean package
java -jar target\dependency\webapp-runner.jar target\myapplication.war
```
the application throws NullPointerException at the first DataSource instantation. It seems to be a hint that WebappRunner is actually not finding the context.xml file inside the WAR (even if is there).

No improvement as well if I specify the context.xml externally:
```
java -jar target\dependency\webapp-runner.jar --context-xml src\main\webapp\META-INF\context.xml target\myapplication.war
```
Any ideas on what could be wrong here?
Thanks!

**Comment by carlomorelli** [comment]
Forgot to mention:
Tomcat 8.5.23
Webapp runner 8.5.23.0

**Comment by Malax** [comment]
Hello! Since this is an old issue and many things have changed since it was opened I will close it for now. Feel absolutely free to re-open it if it is still relevant so we can work on it! :)
