### ISSUE TITLE
Keystore alias missing in documentation

### ISSUE THREAD

**Issue by hgspch** [heroku/webapp-runner#85]
In order to have SSL, using :
`-Djavax.net.ssl.keyStore=, -Djavax.net.ssl.keyStorePassword=, --enable-ssl`
I had to add :
`Djavax.net.ssl.keyStoreAlias=mydomain.com` 
 (Alias can be found by opening the .jks with Portecle, first column in the main view)

**Comment by Malax** [comment]
Hello! Since this is an old issue and many things have changed since it was opened I will close it for now. Feel absolutely free to re-open it if it is still relevant so we can work on it! :)
