### ISSUE TITLE
Option to use a custom server.xml?

### ISSUE THREAD

**Issue by zemian** [heroku/webapp-runner#86]
Hi there, I love your project and the easy of use! Great job by providing this to public!

I have a question/request. Would it be possible to pass a customized tomcat server.xml file to the webapp-runner instance?

Thanks,
Zemian

**Comment by jkutner** [comment]
Thanks. You can't pass in a `server.xml`, but you can customize most of the config options with command line flags (see the `-A` option in particular).

I will accept a PR for any flags you need. I would probably accept a PR for a `server.xml` too if it can be done elegantly.

**Comment by markamaze** [comment]
I am also having a need for including my own server.xml file.  I think my current issue is related to needing multiple Connector elements, and as far as I can tell, the flags only define a single Connector element?

**Comment by jkutner** [comment]
@markamaze webapp-runner only supports a single connector. If you need more advanced configuration, you'll want to you embedded Tomcat directly.

**Comment by Malax** [comment]
Hello! Since this is an old issue and many things have changed since it was opened I will close it for now. Feel absolutely free to re-open it if it is still relevant so we can work on it! :)
